$(document).ready(function () {
   $('.trigger_popup_fricc').click(function(){
      $('.hover_bkgr_fricc').show();
   });
   $('.hover_bkgr_fricc').click(function(){
       $('.hover_bkgr_fricc').hide();
   });
   $('.popupCloseButton').click(function(){
       $('.hover_bkgr_fricc').hide();
   });
 });
 $(document).ready(function () {
    $('.trigger_popup_fricc1').click(function(){
       $('.hover_bkgr_fricc1').show();
    });
    $('.hover_bkgr_fricc1').click(function(){
        $('.hover_bkgr_fricc1').hide();
    });
    $('.popupCloseButton1').click(function(){
        $('.hover_bkgr_fricc1').hide();
    });
  });
  $(document).ready(function () {
     $('.trigger_popup_fricc2').click(function(){
        $('.hover_bkgr_fricc2').show();
     });
     $('.hover_bkgr_fricc2').click(function(){
         $('.hover_bkgr_fricc2').hide();
     });
     $('.popupCloseButton2').click(function(){
         $('.hover_bkgr_fricc2').hide();
     });
   });
   $(document).ready(function () {
      $('.trigger_popup_fricc3').click(function(){
         $('.hover_bkgr_fricc3').show();
      });
      $('.hover_bkgr_fricc3').click(function(){
          $('.hover_bkgr_fricc3').hide();
      });
      $('.popupCloseButton3').click(function(){
          $('.hover_bkgr_fricc3').hide();
      });
    });
    $(document).ready(function () {
       $('.trigger_popup_fricc4').click(function(){
          $('.hover_bkgr_fricc4').show();
       });
       $('.hover_bkgr_fricc4').click(function(){
           $('.hover_bkgr_fricc4').hide();
       });
       $('.popupCloseButton4').click(function(){
           $('.hover_bkgr_fricc4').hide();
       });
     });
    $(document).ready(function () {
       $('.trigger_popup_fricc_pdf').click(function(){
          $('.hover_bkgr_fricc_pdf').show();
       });
       $('.hover_bkgr_fricc_pdf').click(function(){
           $('.hover_bkgr_fricc_pdf').hide();
       });
       $('.popupCloseButton_pdf').click(function(){
           $('.hover_bkgr_fricc_pdf').hide();
       });
     });
     $(document).ready(function () {
        $('.trigger_popup_fricc1_pdf').click(function(){
           $('.hover_bkgr_fricc1_pdf').show();
        });
        $('.hover_bkgr_fricc1_pdf').click(function(){
            $('.hover_bkgr_fricc1_pdf').hide();
        });
        $('.popupCloseButton1_pdf').click(function(){
            $('.hover_bkgr_fricc1_pdf').hide();
        });
      });
     $(document).ready(function () {
        $('.trigger_popup_fricc_PDF').click(function(){
           $('.hover_bkgr_fricc_PDF').show();
        });
        $('.hover_bkgr_fricc_PDF').click(function(){
            $('.hover_bkgr_fricc_PDF').hide();
        });
        $('.popupCloseButton_PDF').click(function(){
            $('.hover_bkgr_fricc_PDF').hide();
        });
      });
      $(document).ready(function () {
         $('.trigger_popup_fricc_PDF1').click(function(){
            $('.hover_bkgr_fricc_PDF1').show();
         });
         $('.hover_bkgr_fricc_PDF1').click(function(){
             $('.hover_bkgr_fricc_PDF1').hide();
         });
         $('.popupCloseButton_PDF1').click(function(){
             $('.hover_bkgr_fricc_PDF1').hide();
         });
       });
       $(document).ready(function () {
          $('.trigger_popup_fricc2_b').click(function(){
             $('.hover_bkgr_fricc2_b').show();
          });
          $('.hover_bkgr_fricc2_b').click(function(){
              $('.hover_bkgr_fricc2_b').hide();
          });
          $('.popupCloseButton2_b').click(function(){
              $('.hover_bkgr_fricc2_b').hide();
          });
        });
        $(document).ready(function () {
           $('.trigger_popup_fricc_3').click(function(){
              $('.hover_bkgr_fricc_3').show();
           });
           $('.hover_bkgr_fricc_3').click(function(){
               $('.hover_bkgr_fricc_3').hide();
           });
           $('.popupCloseButton_3').click(function(){
               $('.hover_bkgr_fricc_3').hide();
           });
         });
         $(document).ready(function () {
            $('.trigger_popup_fricc_1').click(function(){
               $('.hover_bkgr_fricc_1').show();
            });
            $('.hover_bkgr_fricc_1').click(function(){
                $('.hover_bkgr_fricc_1').hide();
              });
            $('.popupCloseButton_1').click(function(){
                $('.hover_bkgr_fricc_1').hide();
            });
          });
